<?php
declare(strict_types=1);

/**
 * @var AbstractEngine $this
 * @var array $parameters
 */
if (!isset($this)) {
    return;
}

use ArrayAccess\TrayDigita\App\Modules\Core\Core;
use ArrayAccess\TrayDigita\Kernel\Interfaces\KernelInterface;
use ArrayAccess\TrayDigita\Module\Modules;
use ArrayAccess\TrayDigita\Util\Filter\ContainerHelper;
use ArrayAccess\TrayDigita\View\Engines\AbstractEngine;

// phpcs:disable Generic.Files.LineLength.TooLong
$core = ContainerHelper::service(Modules::class, $this->getView()->getContainer())
    ->get(Core::class);
$kernel = $core->getKernel();
$translator = $core->getTranslator();
?>
<!DOCTYPE html>
<html class="no-js" lang="<?= htmlspecialchars($parameters['language']??'en');?>">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex, nofollow, noodp, noydir, noarchive">
    <title><?= htmlentities($core->translateContext('Installation', 'installation', 'core-module'));?></title>
    <link rel="stylesheet" href="<?= $this->getView()->getBaseURI('assets@core/css/install.css?v=1.0.0');?>" media="all">
    <script src="<?= $this->getView()->getBaseURI('assets@core/js/install.js?v=1.0.0');?>"></script>
</head>
<body>
<div id="page" class="page-wrapper">
    <?php
    switch ($core->getKernel()->getConfigError()) {
        case KernelInterface::CONFIG_UNAVAILABLE:
            require __DIR__ . '/contents/config-unavailable.phtml';
            break;
        case KernelInterface::CONFIG_EMPTY_FILE:
            require __DIR__ . '/contents/config-empty-file.phtml';
            break;
        case KernelInterface::CONFIG_NOT_FILE:
            require __DIR__ . '/contents/config-not-file.phtml';
            break;
        case KernelInterface::CONFIG_NOT_ITERABLE:
            require __DIR__ . '/contents/config-not-iterable.phtml';
            break;
    }
    ?>
</div>
</body>
</html>
